Configuration:
  name: Default

  Appenders:
    Console:
      name: Console-Appender
      target: SYSTEM_OUT
      PatternLayout:
        pattern: "%d{HH:mm:ss.SSS} [%t] %-5level %X %logger{36} - %msg%n"

  Loggers:
    Root:
      level: info
      AppenderRef:
        ref: Console-Appender
