name: Build Gradle project

on:
  workflow_call:
    secrets:
      aws_key_id:
        required: true
      aws_key:
        required: true

jobs:
  build-gradle-project:
    runs-on:
      - self-hosted
      - ap-ind-medium
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Check branch name
        run: |
          if [[ "${{ github.head_ref }}" =~ ^(revert-|hotfix-|revert_|hotfix_) ]]; then
            echo "Skipping workflow for revert or hotfix branch"
            echo "SKIP_TESTS=true" >> $GITHUB_ENV
          else
            echo "SKIP_TESTS=false" >> $GITHUB_ENV
          fi
      - name: Install Java
        if:  ${{ env.SKIP_TESTS == 'false' }}
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Configure AWS Credentials
        if:  ${{ env.SKIP_TESTS == 'false' }}
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.aws_key_id }}
          aws-secret-access-key: ${{ secrets.aws_key }}
          aws-region: ap-southeast-1
      - name: Setup Gradle
        if: ${{ env.SKIP_TESTS == 'false' }}
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 6.6
      - name: Run build with Gradle Wrapper
        if: ${{ env.SKIP_TESTS == 'false' }}
        run: ./gradlew clean detekMain
